version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test123
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: